import type { Metadata } from 'next';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import "../styles/global.css";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
        <div className="mx-auto  w-full md:w-3/4 px-6">
        <Header />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}
