export interface PostMetadata {
  title: string;
  date: string;
  subtitle: string;
  slug: string;
  image?: string;
  heroImage?: string;
  productImage?: string;
  imageCredit?: string;
  imageSource?: string;
  imageLicense?: string;
  imageAlt?: string;
  gallery?: { src: string; credit?: string; source?: string; license?: string; alt?: string }[];
  author?: string;
  specs?: Record<string, string>;
  pros?: string[];
  cons?: string[];
  authorBio?: string;
  price?: string;
  rating?: number;
  retailerLinks?: Record<string, string>;
  category?: string;
  capacityWh?: number;
  features?: string[];
  guideAwards?: { label: string; reason?: string }[];
  bestFor?: string[];
  skipIf?: string[];
  keyStrength?: string;
  mainTradeoff?: string;
  testedAgainst?: string[];
  notable?: boolean;
  lastReviewed?: string;
  reviewedBy?: string;
  editedBy?: string;
  evidenceLevel?: 'hands-on' | 'spec-analysis' | 'independent-source-synthesis';
  updateHistory?: { date: string; note: string }[];
  evidenceSources?: { label: string; url: string; type?: string }[];
  ratingBreakdown?: {
    overallScore?: number;
    overallRank?: string;
    metrics: { name: string; score: number }[];
  };
}
